// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phlhoohwvqxiglxufbax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobGhvb2h3dnF4aWdseHVmYmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjAxODQsImV4cCI6MjA2MjEzNjE4NH0.osej5WxE3AlyhGf0VQQpMk_sGSTgd3I-oEs61p436VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);